[package]
name = "lpf2html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
maud = "0.25.0"
pulldown-cmark = "0.9.3"
